#!/bin/bash

USERID=$(id -u)

if [ $USERID -ne 0 ]
then
    echo "ERROR: please run this is in root user"
    exit 1 #give anything other then 0 upto 127
else
    echo "you are running in root user"
fi
dnf list installed mysql -y

if [ $? -ne 0 ]
then
    echo " mysql is not installed...going to install "
    dnf install mysql -y
    if [ $? -eq 0 ]
then
    echo "INSTALLING MYSQL....SUCCESS"
else
    echo "INSTALLING MYSQL is failure"
    exit 1
fi


