#!/bin/bash


USERID=$(id -u)

if [ $USERID -ne 0 ]
then
    echo e"ERROR: please run this is in root user" 
    exit 1 #give anything other then 0 upto 127
else
    echo "you are running in root user"
fi
dnf list installed mysql -y
#checks already installed or not if installed $? is 0, then (0 not equal is 0 = false) then
# if not installed $? is not 0 . expression is true

if [ $? -ne 0 ]
then
    echo " mysql is not installed...going to install "
    dnf install mysql -y
    if [ $? -eq 0 ]
   then
        echo "INSTALLING MYSQL....SUCCESS"
   else
        echo "INSTALLING MYSQL is failure"
        exit 1
    fi
else
    echo " mysql is already installed ... nothing to do"
fi