#!bin/bash

NUMBER1=600
NUMBER2=100

TIMESTAMP=$(date)   #it executs date command  and the output of date is store in TIMESTAMP variable
echo "Script exceuted time is : $TIMESTAMP"
SUM=$(($NUMBER1+$NUMBER2))